### ISSUE TITLE
Is it possible to use this to reversely convert IPA  to pinyin?

### ISSUE THREAD

**Issue by fishfree** [stefantaubert/pinyin-to-ipa#1]
Especially converting those in a TextGrid file. Many thanks!

**Comment by stefantaubert** [comment]
A conversion from IPA to pinyin is not possible. It would be difficult to determine the syllables of an IPA transcribed word (which is required to convert each one to pinyin).
One thing that you can do is to use one of these [JSON mapping tables](https://zenodo.org/records/7525638), e.g., [this one](https://zenodo.org/records/7525638/files/pinyin-ipa-map-TONE3-all.json?download=1), which were created using this tool, to reverse lookup the pinyin for single IPA syllables.
